---
jobs:
- name: job-robot
  public: true
  serial: true
  plan:
  - get: resource-tutorial
  - put: resource-docker-image-robot
    params:
      build: tropocicdct/robotframework_image/docker

resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/chcheruk/concourse-tutorial.git
    branch: master

- name: resource-docker-image-robot
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-image-dummy-resource}}
